version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: production
    command:
      - "node"
      - "/app/build/index.js"
    environment:
      NODE_ENV: "production"
    env_file:
      - ".env"
    restart: "always"
